/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.PetManage;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ManagePetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetJPanel
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ManagePetJPanel(JPanel userProcessContainer,UserAccount account,EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business; 
        userEnterprise = business.getEnterpriseDirectory().findEnterpriseID(account.getRole().getEnterpriseID());
        populateRequestTable();
    }
 public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);  
            ArrayList<Pet> worklist = userEnterprise.getPetDirectory().getPetlist();          
            if (worklist != null){               
                for(Pet apl : worklist){
                    Object[] row = new Object[4];
                    row[0]= apl.getID();
                    row[1]= apl.getName();
                    row[2]= apl.getSpecies();
                    row[3]=apl.getAge();       
                    dtm.addRow(row);
                   
                }
            }    
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        addjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NjTextField = new javax.swing.JTextField();
        SjTextField = new javax.swing.JTextField();
        AjTextField = new javax.swing.JTextField();
        refreshJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Species", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 98, 484, 142));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Pet List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 47, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 268, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 273, -1, -1));

        jLabel3.setText("Species");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 273, -1, -1));

        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 273, -1, -1));
        add(NjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 268, 80, -1));
        add(SjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 268, 80, -1));
        add(AjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 268, 80, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int ID= Integer.valueOf(jTable1.getValueAt(row,0).toString());
            Pet pet =(Pet) userEnterprise.getPetDirectory().findPetbyID(ID);
            userEnterprise.getPetDirectory().getPetlist().remove(pet);
            populateRequestTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        String name = NjTextField.getText();
        String species = SjTextField.getText();
        String age = AjTextField.getText();
        Pet pet = new Pet(name, species,age);
        
        userEnterprise.getPetDirectory().getPetlist().add(pet);
        JOptionPane.showMessageDialog(null, "Success");
        populateRequestTable();
    }//GEN-LAST:event_addjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AjTextField;
    private javax.swing.JTextField NjTextField;
    private javax.swing.JTextField SjTextField;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
