/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyPetAdoptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplyPetAdoptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    public ApplyPetAdoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        populateOrgTable();
    }
    
    public void populateOrgTable(){

            DefaultTableModel dtm = (DefaultTableModel) orgjTable.getModel();
            dtm.setRowCount(0);          
            ArrayList<Enterprise> entlist = business.getEnterpriseDirectory().getEnterpriseList();          
            if (entlist != null){               
                for(Enterprise ent : entlist){
                    if (ent.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    Object[] row = new Object[2];
                    row[0]=ent.getEnterpriseID();
                    row[1]=ent.getEnterpriseName();
                    dtm.addRow(row);
                    }
                    
                }
            }    
    } 
    public void populatePetTable(Enterprise org){

            DefaultTableModel dtm = (DefaultTableModel) petjTable.getModel();
            dtm.setRowCount(0);           
            ArrayList<Pet> petlist = org.getPetDirectory().getPetlist();           
            if (petlist != null){                 
                for(Pet pet : petlist){
                    Object[] row = new Object[4];
                    row[0] = pet.getID();
                    row[1] = pet.getName();
                    row[2]=pet.getSpecies();
                    row[3]= pet.getAge();
                    dtm.addRow(row);
                }
            }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        petjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        choosejButton = new javax.swing.JButton();
        ViewjButtonVac = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        RefreshOrgjButton = new javax.swing.JButton();
        ViewjButtonExa = new javax.swing.JButton();

        orgjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(orgjTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Rescue Organiztion List");

        sendjButton.setText("Send Application");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });

        petjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Species", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(petjTable);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Pet List");

        choosejButton.setText("Choose");
        choosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosejButtonActionPerformed(evt);
            }
        });

        ViewjButtonVac.setText("View Pet Vaccine");
        ViewjButtonVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonVacActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        RefreshOrgjButton.setText("Refresh");
        RefreshOrgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshOrgjButtonActionPerformed(evt);
            }
        });

        ViewjButtonExa.setText("View Pet Examination");
        ViewjButtonExa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonExaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backJButton)
                        .addGap(469, 469, 469)
                        .addComponent(RefreshOrgjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(choosejButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendjButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ViewjButtonVac)
                                .addComponent(ViewjButtonExa)))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(RefreshOrgjButton)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(choosejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewjButtonExa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewjButtonVac)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else{
            String ID = petjTable.getValueAt(row, 1).toString();
            Pet pet =(Pet)org.getPetDirectory().findPetbyName(ID);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new FillAdoptionJPanel(userProcessContainer, account, business,pet,org));
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_sendjButtonActionPerformed

    private void choosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosejButtonActionPerformed
        // TODO add your handling code here:
        int row = orgjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else {
            String Name = (String)orgjTable.getValueAt(row, 1);
            org =business.getEnterpriseDirectory().findEnterprise(Name);
            populatePetTable(org);
        }

    }//GEN-LAST:event_choosejButtonActionPerformed

    private void ViewjButtonVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonVacActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else {
            String name = petjTable.getValueAt(row,1).toString();
            Pet pet = org.getPetDirectory().findPetbyName(name);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewPetVacJPanel(userProcessContainer,pet));
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_ViewjButtonVacActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.populateApplicationTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RefreshOrgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshOrgjButtonActionPerformed
        // TODO add your handling code here:
        populateOrgTable();
    }//GEN-LAST:event_RefreshOrgjButtonActionPerformed

    private void ViewjButtonExaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonExaActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else {
            String name = petjTable.getValueAt(row,1).toString();
            Pet pet = org.getPetDirectory().findPetbyName(name);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewPetExaJPanel(userProcessContainer,pet));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_ViewjButtonExaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshOrgjButton;
    private javax.swing.JButton ViewjButtonExa;
    private javax.swing.JButton ViewjButtonVac;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton choosejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orgjTable;
    private javax.swing.JTable petjTable;
    private javax.swing.JButton sendjButton;
    // End of variables declaration//GEN-END:variables
}
