/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EuthanasiaRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.HospitalRole.DoctorJPanel;

/**
 *
 * @author junyaoli
 */

public class ViewEuApplicationJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private  Enterprise userEnterprise;
    EuthanasiaRequest request;
    /**
     * Creates new form ViewEuApplicationJPanel
     */
    public ViewEuApplicationJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, EuthanasiaRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.request=request;
        System.out.println(request.getSender());
        Pet pet = request.getPet();
        reasonjTextField.setText(request.getReason());
        petagejTextField.setText(pet.getAge());
        petspeciejTextField.setText(pet.getSpecies());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reasonjTextField = new javax.swing.JTextField();
        petspeciejTextField = new javax.swing.JTextField();
        petagejTextField = new javax.swing.JTextField();
        canceljButton = new javax.swing.JButton();
        exacutejButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 28, -1, -1));

        jLabel1.setText("Reason");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 115, -1, -1));

        jLabel2.setText("Pet Species");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 178, -1, -1));

        jLabel3.setText("Pet Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 227, -1, -1));
        add(reasonjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 88, 185, 70));
        add(petspeciejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 173, 185, -1));
        add(petagejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 217, 185, -1));

        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });
        add(canceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 310, -1, -1));

        exacutejButton.setText("Exacute");
        exacutejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exacutejButtonActionPerformed(evt);
            }
        });
        add(exacutejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorJPanel dwjp = (DoctorJPanel) component;
        dwjp.populateEuTable();
        dwjp.populateExaminationTable();
        dwjp.populateVaccineTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void exacutejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exacutejButtonActionPerformed
        // TODO add your handling code here:
        request.setResult("Euthanasia");
        request.setResolveDate(new Date());
        request.setStatus("Finished");
        JOptionPane.showMessageDialog(null, "Cancel request");
    }//GEN-LAST:event_exacutejButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        request.setResult("Cancel");
        request.setResolveDate(new Date());
        request.setStatus("Finished");
        JOptionPane.showMessageDialog(null, "Confirm request");
    }//GEN-LAST:event_canceljButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JButton exacutejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField petagejTextField;
    private javax.swing.JTextField petspeciejTextField;
    private javax.swing.JTextField reasonjTextField;
    // End of variables declaration//GEN-END:variables
}
