/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.Pet;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EuthanasiaRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyEuthanasiaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EuthanasiaJPanel
     */
       private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ApplyEuthanasiaJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount account,Enterprise userEnterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userEnterprise=userEnterprise;
        this.account=account;
        this.business=business; 
        initPetBox();
        initcompanyBox();  
    }

    public void initPetBox(){
            petjComboBox.removeAllItems();
            List<Pet> petlist = userEnterprise.getPetDirectory().getPetlist();
            for (Pet object : petlist) {
                petjComboBox.addItem(object.getName());
        }
    }
      public void initcompanyBox(){
            companyjComboBox.removeAllItems();
            List<Enterprise> petlist = business.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise object : petlist) {
                if (!object.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    companyjComboBox.addItem(object.getEnterpriseName());
                }
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SendNewjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        petjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ReasonjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyjComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Application to Hospital");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 42, -1, -1));

        SendNewjButton.setText("Send new Application");
        SendNewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendNewjButtonActionPerformed(evt);
            }
        });
        add(SendNewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        jLabel3.setText("Pet");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        petjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(petjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel4.setText("Reason");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        ReasonjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReasonjTextFieldActionPerformed(evt);
            }
        });
        add(ReasonjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, 76));

        jLabel5.setText("Enterprise");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        companyjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(companyjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 128, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void ReasonjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReasonjTextFieldActionPerformed

    private void SendNewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendNewjButtonActionPerformed
        // TODO add your handling code here:
        if (!ReasonjTextField.getText().isEmpty()) {
        Enterprise euEnterprise = business.getEnterpriseDirectory().findEnterprise(companyjComboBox.getSelectedItem().toString());
        String reason = ReasonjTextField.getText();
        Pet pet = userEnterprise.getPetDirectory().findPetbyName(petjComboBox.getSelectedItem().toString());
        String title = titlejTextField.getText();
          
        EuthanasiaRequest euthunisiaRequest= new EuthanasiaRequest(title,"EuthanasiaRequest",reason, pet);
        euthunisiaRequest.setReceiver(euEnterprise.getEnterpriseName());
        euthunisiaRequest.setSender(userEnterprise.getEnterpriseName());
        euthunisiaRequest.setStatus("pending");
      
           
        euEnterprise.getWorkQueue().getWorkRequestList().add(euthunisiaRequest);
        userEnterprise.getWorkQueue().getWorkRequestList().add(euthunisiaRequest);
         JOptionPane.showMessageDialog(null, "Send successfully");       
        }else
            JOptionPane.showMessageDialog(null, "Please add a Reason");
        
    }//GEN-LAST:event_SendNewjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ReasonjTextField;
    private javax.swing.JButton SendNewjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> companyjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> petjComboBox;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
