/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.Pet;

import userinterface.OrganizationRole.Pet.ViewExamResultPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.ExaminationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyExaminationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form YourPetsJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ApplyExaminationJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount account,Enterprise userEnterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business; 
        this.userEnterprise=userEnterprise;
        initHosbox();
        initPetbox();
    }
    private void initHosbox() {
       HosjComboBox.removeAllItems();
       List<Enterprise> Hos = business.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise hospital : Hos) {
             if (!hospital.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    HosjComboBox.addItem(hospital.getEnterpriseName());
                }     
        }
    }
    private void initPetbox() {
       PetjComboBox.removeAllItems();
       List<Pet> petlist = userEnterprise.getPetDirectory().getPetlist();
        for (Pet pet : petlist) {
            PetjComboBox.addItem(pet.getName());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        PetjComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HosjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Medical Eamination Application");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 47, -1, -1));

        sendjButton.setText("Send Application");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });
        add(sendjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        PetjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(PetjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jLabel2.setText("My Pets");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel3.setText("Hospital");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        HosjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(HosjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel4.setText("Title:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
      String hospitalName=  HosjComboBox.getSelectedItem().toString();
      String petName = PetjComboBox.getSelectedItem().toString();
      Enterprise hospital= business.getEnterpriseDirectory().findEnterprise(hospitalName);
      Pet pet = userEnterprise.getPetDirectory().findPetbyName(petName);
      String title = titlejTextField.getText();
      
      ExaminationRequest e = new ExaminationRequest(title, "ExaminationRequest",pet);
      e.setTitle(title);
      e.setReceiver(hospital.getEnterpriseName());
      e.setSender(userEnterprise.getEnterpriseName());
      e.setStatus("Pending");
      e.setResolveDate(new Date());
      hospital.getWorkQueue().getWorkRequestList().add(e);
      userEnterprise.getWorkQueue().getWorkRequestList().add(e);
      JOptionPane.showMessageDialog(null,"Success");
    }//GEN-LAST:event_sendjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HosjComboBox;
    private javax.swing.JComboBox<String> PetjComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sendjButton;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
