/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.Pet;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EuthanasiaRequest;
import Business.WorkQueue.ExaminationRequest;
import Business.WorkQueue.VaccineRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class InteractionwithHospitalJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private Enterprise userEnterprise;
    /**
     * Creates new form InteractionwithHospitalJPanel
     */
    public InteractionwithHospitalJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        userEnterprise = business.getEnterpriseDirectory().findEnterpriseID(account.getRole().getEnterpriseID());
        populateRequestTable();
    }
    public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);  
            ArrayList<WorkRequest> worklist = userEnterprise.getWorkQueue().getWorkRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    if ((apl.getRequestType().equals("ExaminationRequest"))||(apl.getRequestType().equals("EuthanasiaRequest"))||(apl.getRequestType().equals("VaccineRequest"))) {
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                    }
                   
                }
            }    
    } 
    public void populateSearchTable(WorkRequest apl){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);      
                    Object[] row = new Object[9];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getRequestType();
                    row[3]= apl.getSender();
                    row[4]=apl.getReceiver();
                    row[5]=apl.getRequestDate();
                    row[6]=apl.getResolveDate();
                    row[7]=apl.getStatus();
                    row[8]=apl.getResult();
                    dtm.addRow(row);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        examinationjButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        DeletejButton = new javax.swing.JButton();
        ViewjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SearchjButton = new javax.swing.JButton();
        searchIDjTextField = new javax.swing.JTextField();
        euthanasiajButton1 = new javax.swing.JButton();
        vaccinejButton2 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Medical Application");

        examinationjButton.setText("Examination Application");
        examinationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinationjButtonActionPerformed(evt);
            }
        });

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Type", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicationjTable);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        DeletejButton.setText("Delete Application");
        DeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButtonActionPerformed(evt);
            }
        });

        ViewjButton.setText("View Application");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });

        CanceljButton.setText("Cancel Application");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Title");

        SearchjButton.setText("Search Application");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });

        euthanasiajButton1.setText("Euthanasia Application");
        euthanasiajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euthanasiajButton1ActionPerformed(evt);
            }
        });

        vaccinejButton2.setText("Vaccine Application");
        vaccinejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinejButton2ActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(refreshJButton)
                                .addGap(208, 208, 208))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeletejButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CanceljButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(searchIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchjButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(examinationjButton)
                        .addGap(18, 18, 18)
                        .addComponent(euthanasiajButton1)
                        .addGap(18, 18, 18)
                        .addComponent(vaccinejButton2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(SearchjButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewjButton)
                    .addComponent(DeletejButton)
                    .addComponent(CanceljButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examinationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euthanasiajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccinejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void examinationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinationjButtonActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new ApplyEuthanasiaJPanel(userProcessContainer,business,account,userEnterprise));
        layout.next(userProcessContainer);            // TODO add your handling code here:
       
    }//GEN-LAST:event_examinationjButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void DeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request = userEnterprise.getWorkQueue().findRequestbyID(requestID);
            userEnterprise.getWorkQueue().getWorkRequestList().remove(request);
            populateRequestTable();
        }
    }//GEN-LAST:event_DeletejButtonActionPerformed

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);  
         
              if (request.getRequestType().equals("ExaminationRequest")) {
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add(new ViewExamResultPanel(userProcessContainer,account,business, (ExaminationRequest)request));
                layout.next(userProcessContainer);
            } if (request.getRequestType().equals("VaccineRequest")) {
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add(new ViewVaccineJPanel(userProcessContainer,account,business,(VaccineRequest) request));
                layout.next(userProcessContainer);
            }
            
        }
    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            String requestEnterprise= (applicationjTable.getValueAt(row,3).toString());
            WorkRequest request =(WorkRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            //            ExaminationRequest request1 = (ExaminationRequest)business.getEnterpriseDirectory().findEnterprise(requestEnterprise).getWorkQueue().findRequestbyID(requestID);
            //            request1.setStatus("Canceled");
            request.setStatus("Canceled");
            request.setResolveDate(new Date());
            populateRequestTable();
        }
    }//GEN-LAST:event_CanceljButtonActionPerformed

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        // TODO add your handling code here:
        String search = searchIDjTextField.getText();
        WorkRequest findAccount = userEnterprise.getWorkQueue().findRequestbyname(search);
        //这里应该返回一个找到用户名字的List  //现在是返回一个网络个体
        populateSearchTable(findAccount);
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void euthanasiajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euthanasiajButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new ApplyExaminationJPanel(userProcessContainer,business,account,userEnterprise));
        layout.next(userProcessContainer);    
    }//GEN-LAST:event_euthanasiajButton1ActionPerformed

    private void vaccinejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinejButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new ApplyVaccineJPanel(userProcessContainer,business,account,userEnterprise));
        layout.next(userProcessContainer);    
    }//GEN-LAST:event_vaccinejButton2ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton;
    private javax.swing.JButton DeletejButton;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton euthanasiajButton1;
    private javax.swing.JButton examinationjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField searchIDjTextField;
    private javax.swing.JButton vaccinejButton2;
    // End of variables declaration//GEN-END:variables
}
