/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class ViewAdoptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyApplicationJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Pet pet;
    private Enterprise org;
    private AdoptionRequest request;
    
   
    public ViewAdoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,AdoptionRequest request){
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.request=request;
             initText();
    }
   public void initText(){
         
        titlejTextField.setText(String.valueOf(request.getTitle()));       
        budgetjTextField.setText(String.valueOf(request.getBudget()));
        descriptionjTextField.setText(request.getSelfeDes());
   
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        budgetjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionjTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        ModifyjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Please fill in your information !");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 75, -1, -1));

        jLabel4.setText("Annual Budget");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));
        add(budgetjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 119, -1));

        jLabel5.setText("Personal Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        add(descriptionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 119, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        ModifyjButton.setText("Modify");
        ModifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyjButtonActionPerformed(evt);
            }
        });
        add(ModifyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 119, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.populateApplicationTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void ModifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyjButtonActionPerformed
        // TODO add your handling code here:              
        int budget = Integer.valueOf(budgetjTextField.getText());
        String description = descriptionjTextField.getText();
        String title = titlejTextField.getText();
        
        request.setBudget(budget);
        request.setSelfeDes(description);
        request.setTitle(title);
        
        JOptionPane.showMessageDialog(null,"Edit successfully");
    }//GEN-LAST:event_ModifyjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModifyjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField budgetjTextField;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
