/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.ApplicationOfVolunteer;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author junyaoli
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetadoptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        
        populateApplicationTable();
        
       
    }
    public void populateApplicationTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);                 
            
            ArrayList<WorkRequest> worklist = account.getWorkQueue().getWorkRequestList();   
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                }
            }
            
    }
            
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ViewjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        ApplyanAdoptionjButton = new javax.swing.JButton();
        ToBeVolunteerjButton = new javax.swing.JButton();
        RefreshjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicationjTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 631, 164));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setText("My Application");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        ViewjButton.setText("View");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });
        add(ViewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });
        add(canceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        ApplyanAdoptionjButton.setText("Apply an adoption");
        ApplyanAdoptionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyanAdoptionjButtonActionPerformed(evt);
            }
        });
        add(ApplyanAdoptionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        ToBeVolunteerjButton.setText("To be a volunteer");
        ToBeVolunteerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeVolunteerjButtonActionPerformed(evt);
            }
        });
        add(ToBeVolunteerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        RefreshjButton.setText("Refresh");
        RefreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshjButtonActionPerformed(evt);
            }
        });
        add(RefreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int id=Integer.valueOf(applicationjTable.getValueAt(row, 0).toString());
            String type = account.getWorkQueue().findRequestbyID(id).getClass().getSimpleName();
             if (type.equals("AdoptionRequest")) {
            AdoptionRequest request =(AdoptionRequest) account.getWorkQueue().findRequestbyID(id);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewAdoptionJPanel(userProcessContainer,account,business,request));
            layout.next(userProcessContainer);          
             }else if (type.equals("ApplicationOfVolunteer")) {
             ApplicationOfVolunteer request =(ApplicationOfVolunteer) account.getWorkQueue().findRequestbyID(id);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewVolunteerJPanel(userProcessContainer,account,business,request));
            layout.next(userProcessContainer);
            } else
                 System.out.println(type);
        }

    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) account.getWorkQueue().findRequestbyID(requestID);

            request.setStatus("Canceled");
            request.setResolveDate(new Date());
            populateApplicationTable();
        }
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) account.getWorkQueue().findRequestbyID(requestID);
            account.getWorkQueue().getWorkRequestList().remove(request);
            populateApplicationTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void ApplyanAdoptionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyanAdoptionjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ApplyPetAdoptionJPanel(userProcessContainer,account,business));
            layout.next(userProcessContainer);
    }//GEN-LAST:event_ApplyanAdoptionjButtonActionPerformed

    private void ToBeVolunteerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeVolunteerjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ApplyVolunteerJPanel(userProcessContainer,account,business));
            layout.next(userProcessContainer);
    }//GEN-LAST:event_ToBeVolunteerjButtonActionPerformed

    private void RefreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshjButtonActionPerformed
        // TODO add your handling code here:
        populateApplicationTable();
    }//GEN-LAST:event_RefreshjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyanAdoptionjButton;
    private javax.swing.JButton RefreshjButton;
    private javax.swing.JButton ToBeVolunteerjButton;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton canceljButton;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
