/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class FillAdoptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyApplicationJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Pet pet;
    private Enterprise org;
    private AdoptionRequest request;
    
    public FillAdoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Pet pet, Enterprise org) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.org=org;
        this.pet = pet;
    }
    public FillAdoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,AdoptionRequest request){
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.request=request;
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        budgetjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionjTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        ApplyjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Please fill in your information !");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 75, -1, -1));

        jLabel4.setText("Annual Budget");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));
        add(budgetjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 119, -1));

        jLabel5.setText("Personal Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        add(descriptionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 119, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        ApplyjButton.setText("Apply");
        ApplyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyjButtonActionPerformed(evt);
            }
        });
        add(ApplyjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 119, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ApplyPetAdoptionJPanel dwjp = (ApplyPetAdoptionJPanel) component;
        dwjp.populateOrgTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void ApplyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyjButtonActionPerformed
        // TODO add your handling code here:
//        UserAccount receiver = business.getUserAccountDirectory().findUser(org.getEnterpriseName());
        
        WorkQueue entworkqeueue = org.getWorkQueue();
        WorkQueue userWorkQueue=account.getWorkQueue();
        
        int budget = Integer.valueOf(budgetjTextField.getText());
        String description = descriptionjTextField.getText();
        String title = titlejTextField.getText();
        
        AdoptionRequest request = new AdoptionRequest(title,"AdoptionRequest",description,budget,pet);
        request.setReceiver(org.getEnterpriseName());
        request.setSender(account.getUsername());
        request.setStatus("Pending");
        
        entworkqeueue.getWorkRequestList().add(request);
        userWorkQueue.getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null,"Send successfully");
    }//GEN-LAST:event_ApplyjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField budgetjTextField;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
