/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalRole;

import Business.EcoSystem;
import Business.Pet.ExaminationResult;
import Business.Pet.Pet;
import Business.Pet.VaccineResult;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ExaminationRequest;
import Business.WorkQueue.VaccineRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class ViewVaccineJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private VaccineRequest request;
    /**
     * Creates new form ViewVaccineJPanel
     */
    public ViewVaccineJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, VaccineRequest request) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.request=request;
        initRequest();
    }
     public void initRequest(){
       
        namejTextField.setText(request.getVaccinename());       
        introductionjTextField.setText(request.getVaccineintroduction());
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introductionjTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirmjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(introductionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 117, 226, 168));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, -1, -1));

        jLabel1.setText("Vaccine name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 84, -1, -1));
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 79, 226, -1));

        jLabel2.setText("Vaccine introduction");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 193, -1, -1));

        confirmjButton.setText("Confirm");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });
        add(confirmjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 339, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
        request.setVaccineintroduction(introductionjTextField.getText());   
        request.setVaccinename(namejTextField.getText());      
        
        request.setStatus("Finished");
        request.setResult("Vaccined");
        request.setResolveDate(new Date());
       
       
        Pet pet = request.getPet();
        VaccineResult result =new VaccineResult();
        result.setInjectDate(new Date());
        result.setVaccinename(namejTextField.getText());   
        result.setVaccineintroduction(introductionjTextField.getText());    
        pet.setVaccineResult(result);
        JOptionPane.showMessageDialog(null,"Success");
    }//GEN-LAST:event_confirmjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JTextField introductionjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField namejTextField;
    // End of variables declaration//GEN-END:variables
}
