/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Organization;

import Business.Department.Department;
import Business.Department.DepartmentDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class OrganizationManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagementJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise userEnterprise;
    private Department cDepartment;
    public OrganizationManagementJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        userEnterprise = business.getEnterpriseDirectory().findEnterpriseID(account.getRole().getEnterpriseID());
        populateRequestTable();
    }
public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);      
            DepartmentDirectory worklist= userEnterprise.getDepartmentDirectory();
          
            if (worklist != null){  
                for(Department request : worklist.getDepartmentDirectory()){
                    Object[] row = new Object[2];
                    row[0]=request.getDepartmentID();
                    row[1]=request.getName();
                    dtm.addRow(row);
                }
            }     
    }
 public void populateEmployeeTable(Department department){

            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);      
            EmployeeDirectory worklist= department.getEmployeeDirectory();       
            if (worklist != null){  
                for(Employee request : worklist.getEmployeeList()){
                    Object[] row = new Object[3];
                    row[0]=request.getId();
                    row[1]=request.getName();    
                    row[2]=request.getRegisterTime();
                    dtm.addRow(row);
                }
            }     
    }
    public void populateResearchTable(Employee request){

            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);          
                    Object[] row = new Object[3];
                    row[0]=request.getId();
                    row[1]=request.getName();
                    row[2]=request.getRegisterTime();
                    dtm.addRow(row);                    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SearchjButton = new javax.swing.JButton();
        deleteDepartmentjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ViewjButton = new javax.swing.JButton();
        RefreshjButton = new javax.swing.JButton();
        namejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addEmployeejButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addjButton = new javax.swing.JButton();
        deleteEmployeejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewEmployeejButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");

        jLabel4.setText("Employee List：");

        SearchjButton.setText("Search");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });

        deleteDepartmentjButton.setText("Delete Department");
        deleteDepartmentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDepartmentjButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Department List：");

        jLabel5.setText("Name");

        ViewjButton.setText("View EmplopyeeList");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });

        RefreshjButton.setText("Refresh");
        RefreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        addEmployeejButton.setText("Add Employee");
        addEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeejButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "RegisterTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        addjButton.setText("Add Department");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        deleteEmployeejButton.setText("Delete Employee");
        deleteEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeejButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        viewEmployeejButton.setText("View Employee");
        viewEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(425, 425, 425)
                                        .addComponent(RefreshjButton))
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addjButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteDepartmentjButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ViewjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addEmployeejButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteEmployeejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewEmployeejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(RefreshjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addjButton)
                    .addComponent(deleteDepartmentjButton)
                    .addComponent(ViewjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchjButton)
                    .addComponent(addEmployeejButton)
                    .addComponent(deleteEmployeejButton)
                    .addComponent(viewEmployeejButton)
                    .addComponent(jLabel5)
                    .addComponent(namejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        // TODO add your handling code here:
        String search = namejTextField.getText();
        Employee findAccount = cDepartment.getEmployeeDirectory().findEmployee(search);
        //这里应该返回一个找到用户名字的List  //现在是返回一个网络个体
        populateResearchTable(findAccount);
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
        
         int row = jTable1.getSelectedRow();
         if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            String id=(jTable1.getValueAt(row, 1).toString());
             cDepartment =(Department) userEnterprise.getDepartmentDirectory().findDepartment(id);         
            populateEmployeeTable(cDepartment);
        }
    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void RefreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshjButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();      
        populateEmployeeTable(cDepartment);
    }//GEN-LAST:event_RefreshjButtonActionPerformed

    private void addEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeejButtonActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new CreateOrgEmpJPanel( userProcessContainer ,business ,userEnterprise ,cDepartment));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addEmployeejButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        String name = namejTextField.getText();
        userEnterprise.getDepartmentDirectory().createOrganization(name);
        populateRequestTable();
    }//GEN-LAST:event_addjButtonActionPerformed

    private void deleteDepartmentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDepartmentjButtonActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
         if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            String id=(jTable1.getValueAt(row, 1).toString());
            Department request =(Department) userEnterprise.getDepartmentDirectory().findDepartment(id);         
            userEnterprise.getDepartmentDirectory().getDepartmentDirectory().remove(request);
            populateRequestTable();
        }
    }//GEN-LAST:event_deleteDepartmentjButtonActionPerformed

    private void deleteEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeejButtonActionPerformed
        // TODO add your handling code here: 
        int row = jTable2.getSelectedRow();
         if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            String id=(jTable2.getValueAt(row, 1).toString());
            Employee request =(Employee) cDepartment.getEmployeeDirectory().findEmployee(id);         
             cDepartment.getEmployeeDirectory().getEmployeeList().remove(request);
             populateEmployeeTable(cDepartment);
        }
    }//GEN-LAST:event_deleteEmployeejButtonActionPerformed

    private void viewEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeejButtonActionPerformed
        // TODO add your handling code here:
          int row = jTable2.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null,"Please select a row!", "get Request",JOptionPane.ERROR_MESSAGE);
        }else{
            String name = jTable2.getValueAt(row,1).toString();
            Employee employee = cDepartment.getEmployeeDirectory().findEmployee(name);       
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewOrgEmpJPanel(userProcessContainer, business, employee));
            layout.next(userProcessContainer);
                    
        }
    }//GEN-LAST:event_viewEmployeejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshjButton;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JButton addEmployeejButton;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton deleteDepartmentjButton;
    private javax.swing.JButton deleteEmployeejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JButton viewEmployeejButton;
    // End of variables declaration//GEN-END:variables
}
