/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdmin;

import Business.Department.Department;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.OrganizationAdminRole;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.Role.WorkerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.List;
import java.util.UUID;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class CreateAccountJPane extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPane
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Employee newEmployee;
    public CreateAccountJPane(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        initrolebox();
        
        initnetworkbox();
    }
  private void initrolebox() {   
            rolejComboBox.removeAllItems(); 
            rolejComboBox.addItem(Role.RoleType.Customer.getValue());
            rolejComboBox.addItem(Role.RoleType.Doctor.getValue());
            rolejComboBox.addItem(Role.RoleType.HospitalAdmin.getValue());
            rolejComboBox.addItem(Role.RoleType.OrganizationAdmin.getValue());
            rolejComboBox.addItem(Role.RoleType.Worker.getValue());
            rolejComboBox.addItem(Role.RoleType.SysAdmin.getValue());        
    }
  private void initenterprisebox(Network network) {
      List<Enterprise> list = network.getEnterpriseDirectory().getEnterpriseList();
       enterprisejComboBox.removeAllItems(); 
        for (Enterprise obj : list) {
            enterprisejComboBox.addItem(obj.getEnterpriseName());
        }
    }
  private void initdepartmentbox(Enterprise enterprise) {
       List<Department> list = enterprise.getDepartmentDirectory().getDepartmentDirectory();
       departmentjComboBox.removeAllItems(); 
        for (Department obj : list) {
            departmentjComboBox.addItem(obj.getName());
        }
    }
  private void initnetworkbox() {
       List<Network> list = system.getNetworkdirectory().getNetworkdirectory();
       networkjComboBox.removeAllItems(); 
        for (Network obj : list) {
            networkjComboBox.addItem(obj.getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rolejComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkjComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterprisejComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        departmentjComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        EmlpoyeeNamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        genderjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmjButton = new javax.swing.JButton();
        usernamejTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(passwordjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 381, 96, -1));

        jLabel9.setText("Age");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 173, -1, -1));

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 354, -1, -1));

        rolejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(rolejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 129, -1, -1));

        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 211, -1, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 386, -1, -1));

        networkjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBoxActionPerformed(evt);
            }
        });
        add(networkjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 166, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel11.setText("Employee Information");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 77, -1, -1));

        jLabel3.setText("Employee Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 135, -1, 20));

        enterprisejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterprisejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisejComboBoxActionPerformed(evt);
            }
        });
        add(enterprisejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 205, -1, -1));

        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 133, -1, -1));

        departmentjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(departmentjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 238, -1, -1));

        jLabel5.setText("Network");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 170, -1, -1));
        add(EmlpoyeeNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 96, 30));
        add(AgejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 168, 96, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel8.setText("UserAccount Information");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 288, -1, -1));
        add(genderjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 206, 96, -1));

        jLabel6.setText("Enterprise");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 209, -1, -1));

        jLabel7.setText("Department");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 242, -1, -1));

        confirmjButton.setText("Confirm");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });
        add(confirmjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 333, 82, 68));
        add(usernamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 349, 96, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
        String Username=usernamejTextField.getText();
        String password=passwordjTextField.getText();
        String Employeename=EmlpoyeeNamejTextField.getText();
        int age=Integer.parseInt(AgejTextField.getText());
        String gender=genderjTextField.getText() ;
        int id =getUUID();
        
        Network net=system.getNetworkdirectory().findNetWork(networkjComboBox.getSelectedItem().toString());
        Enterprise ent=system.getEnterpriseDirectory().findEnterprise(enterprisejComboBox.getSelectedItem().toString());
        
        String roleType= rolejComboBox.getSelectedItem().toString();
        String departmentType=departmentjComboBox.getSelectedItem().toString();
        
//         Employee newEmployee=system.getEmployeeDirectory().createEmployee(Employeename, Department.DepartmentType.SystemOrg);     
          newEmployee=system.getEmployeeDirectory().createEmployee(Employeename);
          newEmployee.setAge(age);
          newEmployee.setSex(gender);
          newEmployee.setId(id);
       
          
          if (roleType.equals(Role.RoleType.Customer.getValue())) {
             JOptionPane.showMessageDialog(null, "Create successfully");
              UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new CustomerRole("Customer",ent.getEnterpriseID() )); 
              account.setId(id);
          }if (roleType.equals(Role.RoleType.Doctor.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new DoctorRole("Doctor",ent.getEnterpriseID() )); 
             account.setId(id);
          }if (roleType.equals(Role.RoleType.HospitalAdmin.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new HospitalAdminRole("HospitalAdmin",ent.getEnterpriseID() )); 
            account.setId(id);
          }if (roleType.equals(Role.RoleType.OrganizationAdmin.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new OrganizationAdminRole("OrganizationAdmin",ent.getEnterpriseID() )); 
            account.setId(id);
          }if (roleType.equals(Role.RoleType.Worker.getValue())) {
             UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new WorkerRole("Worker",ent.getEnterpriseID() )); 
             account.setId(id);
          }if (roleType.equals(Role.RoleType.SysAdmin.getValue())) {
             UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new SystemAdminRole("SysAdmin",ent.getEnterpriseID() )); 
             account.setId(id);
          }
          
    }//GEN-LAST:event_confirmjButtonActionPerformed

    private void enterprisejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisejComboBoxActionPerformed
        // TODO add your handling code here: 
     
        try {     
             Network net=system.getNetworkdirectory().findNetWork(networkjComboBox.getSelectedItem().toString());
             Enterprise ent=net.getEnterpriseDirectory().findEnterprise(enterprisejComboBox.getSelectedItem().toString());
             System.out.println(ent.getEnterpriseName());
             initdepartmentbox(ent);
        } catch (Exception e) {    
        }

    }//GEN-LAST:event_enterprisejComboBoxActionPerformed

    private void networkjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBoxActionPerformed
        // TODO add your handling code here:      
 
         try {
             Network net=system.getNetworkdirectory().findNetWork(networkjComboBox.getSelectedItem().toString());
            initenterprisebox(net);
        } catch (Exception e) {
       
        }            
    }//GEN-LAST:event_networkjComboBoxActionPerformed
 public int getUUID(){
        String id = null;
        UUID uuid = UUID.randomUUID();
        id=uuid.toString();
        
        id=id.replace("-", "");
        int num= id.hashCode();
        num=Math.abs(num);
        return  num;      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JTextField EmlpoyeeNamejTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JComboBox<String> departmentjComboBox;
    private javax.swing.JComboBox<String> enterprisejComboBox;
    private javax.swing.JTextField genderjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> networkjComboBox;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JComboBox<String> rolejComboBox;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
