/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdmin;

import Business.Department.Department;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.OrganizationAdminRole;
import Business.Role.Role;
import static Business.Role.Role.RoleType.VolunteerMgn;
import Business.Role.SystemAdminRole;
import Business.Role.VolunteerMgn;
import Business.Role.WorkerRole;
import Business.UserAccount.UserAccount;
import static com.sun.xml.internal.ws.util.JAXWSUtils.getUUID;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class CreateEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeJPanel
     */
    private JPanel userProcessContainer;
    private  EcoSystem system;
    private  Network network ;
    private  Enterprise enterprise ;
    private  Department department;
    public CreateEmployeeJPanel(JPanel userProcessContainer, EcoSystem system, Network network ,Enterprise enterprise ,Department department) {
        initComponents();
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network=network;
        this.department=department;
        initrolebox();
        
        NetworkTextField.setEditable(false);
        EnterprisejTextField.setEditable(false);
        DepartmentjTextField.setEditable(false);
        NetworkTextField.setText(network.getName());
        EnterprisejTextField.setText(enterprise.getEnterpriseName());
        DepartmentjTextField.setText(department.getName());
        
    }
      private void initrolebox() {   
            rolejComboBox.removeAllItems(); 
            rolejComboBox.addItem(Role.RoleType.Doctor.getValue());
            rolejComboBox.addItem(Role.RoleType.HospitalAdmin.getValue());
            rolejComboBox.addItem(Role.RoleType.OrganizationAdmin.getValue());
            rolejComboBox.addItem(Role.RoleType.Worker.getValue());
            
            rolejComboBox.addItem(Role.RoleType.VolunteerMgn.getValue());    
            rolejComboBox.addItem(Role.RoleType.SysAdmin.getValue());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rolejComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EmlpoyeeNamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        genderjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmjButton = new javax.swing.JButton();
        usernamejTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        NetworkTextField = new javax.swing.JTextField();
        EnterprisejTextField = new javax.swing.JTextField();
        DepartmentjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(passwordjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 96, -1));

        jLabel9.setText("Age");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        rolejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(rolejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel11.setText("Employee Information");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel3.setText("Employee Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 20));

        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel5.setText("Network");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        add(EmlpoyeeNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 96, 30));
        add(AgejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 96, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel8.setText("UserAccount Information");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
        add(genderjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 96, -1));

        jLabel6.setText("Enterprise");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel7.setText("Department");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        confirmjButton.setText("Confirm");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });
        add(confirmjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 82, 68));
        add(usernamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 96, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));
        add(NetworkTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 96, -1));
        add(EnterprisejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 96, -1));
        add(DepartmentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 96, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
       Employee newEmployee ;
        String Username=usernamejTextField.getText();
        String password=passwordjTextField.getText();
        String Employeename=EmlpoyeeNamejTextField.getText();
        int age=Integer.parseInt(AgejTextField.getText());
        String gender=genderjTextField.getText() ;
        int id =getUUID();

        Network net=network;
        Enterprise ent=enterprise;

        String roleType= rolejComboBox.getSelectedItem().toString();
       newEmployee=department.getEmployeeDirectory().createEmployee(Employeename);
        newEmployee.setAge(age);
        newEmployee.setSex(gender);
        newEmployee.setId(id);

        if (roleType.equals(Role.RoleType.Customer.getValue())) {
            JOptionPane.showMessageDialog(null, "Create successfully");
            UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new CustomerRole("Customer"));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.Doctor.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new DoctorRole("Doctor",ent.getEnterpriseID() ));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.HospitalAdmin.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new HospitalAdminRole("HospitalAdmin",ent.getEnterpriseID() ));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.OrganizationAdmin.getValue())) {
            UserAccount account=  system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new OrganizationAdminRole("OrganizationAdmin",ent.getEnterpriseID() ));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.Worker.getValue())) {
            UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new WorkerRole("Worker",ent.getEnterpriseID() ));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.SysAdmin.getValue())) {
            UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new SystemAdminRole("SysAdmin"));
            account.setId(id);
        }if (roleType.equals(Role.RoleType.VolunteerMgn.getValue())) {
            UserAccount account= system.getUserAccountDirectory().createUserAccount(Username, password, newEmployee, new VolunteerMgn("VolunteerMgn",ent.getEnterpriseID()));
            account.setId(id);
            
        }

    }//GEN-LAST:event_confirmjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageEmployeeJPanel dwjp = (ManageEmployeeJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
 public int getUUID(){
        String id = null;
        UUID uuid = UUID.randomUUID();
        id=uuid.toString();
        
        id=id.replace("-", "");
        int num= id.hashCode();
        num=Math.abs(num);
        return  num;      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JTextField DepartmentjTextField;
    private javax.swing.JTextField EmlpoyeeNamejTextField;
    private javax.swing.JTextField EnterprisejTextField;
    private javax.swing.JTextField NetworkTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JTextField genderjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JComboBox<String> rolejComboBox;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
