/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdmin;

import Business.Department.Department;
import Business.Department.DepartmentDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {
      
    private Department department;
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private  Enterprise enterprise;
    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageEmployeeJPanel(JPanel userProcessContainer,EcoSystem system,Network network , Enterprise enterprise ,Department department) {
        initComponents();       
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.network=network;
        this.enterprise=enterprise;
        this.department=department;
        populateRequestTable();
    }
     public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);      
            EmployeeDirectory worklist= department.getEmployeeDirectory();
          
            if (worklist != null){  
                for(Employee request : worklist.getEmployeeList()){
                    Object[] row = new Object[3];
                    row[0]=request.getId();
                    row[1]=request.getName();
                    row[2]=request.getRegisterTime();
                    dtm.addRow(row);
                }
            }     
    }
    public void populateResearchTable(Employee request){

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);          
                    Object[] row = new Object[3];
                    row[0]=request.getId();
                    row[1]=request.getName();
                    row[2]=request.getRegisterTime();
                    dtm.addRow(row);                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejTextField = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        RefreshjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 259, 85, -1));

        addjButton.setText("Add Employee");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        add(addjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 259, 121, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "RegisterTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 132, 499, 103));

        jButton2.setText("Delete Employee");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 259, 136, -1));

        jLabel1.setText("Employee List：");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 89, -1, -1));

        SearchjButton.setText("Search");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });
        add(SearchjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 259, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 42, -1, -1));

        RefreshjButton.setText("Refresh");
        RefreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshjButtonActionPerformed(evt);
            }
        });
        add(RefreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 84, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 264, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        // TODO add your handling code here:
        String search = namejTextField.getText();
        Employee findAccount = department.getEmployeeDirectory().findEmployee(search);
        //这里应该返回一个找到用户名字的List  //现在是返回一个网络个体
        populateResearchTable(findAccount);
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDepartmentJPanel dwjp = (ManageDepartmentJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RefreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshjButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_RefreshjButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
             CardLayout layout = (CardLayout) userProcessContainer.getLayout();
             userProcessContainer.add(new CreateEmployeeJPanel( userProcessContainer, system, network ,enterprise ,department));
             layout.next(userProcessContainer);
    }//GEN-LAST:event_addjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshjButton;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namejTextField;
    // End of variables declaration//GEN-END:variables
}
