/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdmin;

import Business.Department.Department;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.OrganizationAdminRole;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.Role.WorkerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdk.nashorn.internal.runtime.UserAccessorProperty;

/**
 *
 * @author junyaoli
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
   private JPanel userProcessContainer; 
    private EcoSystem system;
    private UserAccount account;
    
    public ViewAccountJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.account=account;     
        if (!(account.getEmployee()==null)) {
            employeenamejTextField.setText(account.getEmployee().getName());
        AgejTextField.setText(String.valueOf(account.getEmployee().getAge()));
        genderjTextField.setText(account.getEmployee().getSex());
        }       
        passwordjTextField.setText(account.getPassword());
        UsernamejTextField1.setText(account.getUsername());      
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        editjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        employeenamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        genderjTextField = new javax.swing.JTextField();
        UsernamejTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 379, -1, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 411, -1, -1));

        jLabel3.setText("Employee Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        add(passwordjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 406, 96, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel8.setText("UserAccount Information");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 313, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        editjButton.setText("Confirm");
        editjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButtonActionPerformed(evt);
            }
        });
        add(editjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 372, 82, 68));

        jLabel9.setText("Age");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel11.setText("Employee Information");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 77, -1, -1));
        add(employeenamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 96, -1));
        add(AgejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 96, -1));
        add(genderjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 96, -1));
        add(UsernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 374, 96, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
               userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserJPanel dwjp = (ManageUserJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void editjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButtonActionPerformed
        // TODO add your handling code here:
        String Username=UsernamejTextField1.getText();
        String password=passwordjTextField.getText();
        String Employeename=employeenamejTextField.getText();
        int age=Integer.parseInt(AgejTextField.getText());
        String gender=genderjTextField.getText() ;
        
         if (!(account.getEmployee()==null)) {
                Employee newemployee = account.getEmployee();
                newemployee.setAge(age);
        //        newemployee.setDepType(Department.DepartmentType.valueOf(departmentType));
                newemployee.setName(Employeename);
                newemployee.setSex(gender);
        }
       
        account.setPassword(password);
        account.setUsername(Username);
        
//         Employee newEmployee=system.getEmployeeDirectory().createEmployee(Employeename, Department.DepartmentType.SystemOrg);
   
           JOptionPane.showMessageDialog(null, "edit successfully");
    }//GEN-LAST:event_editjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton editjButton;
    private javax.swing.JTextField employeenamejTextField;
    private javax.swing.JTextField genderjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passwordjTextField;
    // End of variables declaration//GEN-END:variables
}
