/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class AdoptionProcess extends javax.swing.JPanel {

    /**
     * Creates new form AdoptionProcess
     */
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private Enterprise userEnterprise;
    public AdoptionProcess(JPanel userProcessContainer,Enterprise userEnterprise ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userEnterprise=userEnterprise;
        this.account=account;
        this.business=business;
            try {
            populateRequestTable();
           
            } catch (Exception e) {
            }
        
    }
       public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);  
            ArrayList<WorkRequest> worklist = userEnterprise.getWorkQueue().getWorkRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                }
            }    
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        enterjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Adoption Application List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ttile", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(applicationjTable);
        if (applicationjTable.getColumnModel().getColumnCount() > 0) {
            applicationjTable.getColumnModel().getColumn(0).setResizable(false);
            applicationjTable.getColumnModel().getColumn(2).setResizable(false);
            applicationjTable.getColumnModel().getColumn(3).setResizable(false);
            applicationjTable.getColumnModel().getColumn(4).setResizable(false);
            applicationjTable.getColumnModel().getColumn(5).setResizable(false);
            applicationjTable.getColumnModel().getColumn(6).setResizable(false);
            applicationjTable.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 631, 164));

        enterjButton.setText("Enter");
        enterjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterjButtonActionPerformed(evt);
            }
        });
        add(enterjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 250, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void enterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterjButtonActionPerformed
        // TODO add your handling code here:
         int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());    
            AdoptionRequest adoptionRequest =(AdoptionRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ReviewApplicationJPanel(userProcessContainer, adoptionRequest));
            layout.next(userProcessContainer);    
        }

    }//GEN-LAST:event_enterjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton enterjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
