/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.PetHealth;

import userinterface.OrganizationRole.PetHealth.ViewExamResultPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.ExaminationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyExaminationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form YourPetsJPanel
     */
        private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ApplyExaminationJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount account,Enterprise userEnterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business; 
        this.userEnterprise=userEnterprise;
        populateApplicationTable();
        initHosbox();
        initPetbox();
    }
    private void initHosbox() {
       HosjComboBox.removeAllItems();
       List<Enterprise> Hos = business.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise hospital : Hos) {
             if (!hospital.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    HosjComboBox.addItem(hospital.getEnterpriseName());
                }     
        }
    }
    private void initPetbox() {
       PetjComboBox.removeAllItems();
       List<Pet> petlist = userEnterprise.getPetDirectory().getPetlist();
        for (Pet pet : petlist) {
            PetjComboBox.addItem(pet.getName());
        }
    }
    public void populateApplicationTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);                 
            
            ArrayList<ExaminationRequest> worklist = userEnterprise.getWorkQueue().getExaminationRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        PetjComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HosjComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();
        DeletejButton = new javax.swing.JButton();
        ViewjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Medical Eamination Application");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 47, -1, -1));

        sendjButton.setText("Send Application");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });
        add(sendjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        PetjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(PetjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel2.setText("My Pets");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel3.setText("Hospital");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        HosjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(HosjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicationjTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 102, 631, 164));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jLabel4.setText("Title:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 90, -1));

        DeletejButton.setText("Delete Application");
        DeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButtonActionPerformed(evt);
            }
        });
        add(DeletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        ViewjButton.setText("View Application");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });
        add(ViewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        CanceljButton.setText("Cancel Application");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });
        add(CanceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
      String hospitalName=  HosjComboBox.getSelectedItem().toString();
      String petName = PetjComboBox.getSelectedItem().toString();
      Enterprise hospital= business.getEnterpriseDirectory().findEnterprise(hospitalName);
      Pet pet = userEnterprise.getPetDirectory().findPet(petName);
      String title = titlejTextField.getText();
      
      ExaminationRequest e = new ExaminationRequest(title, pet);
      e.setTitle(title);
      e.setReceiver(hospital.getEnterpriseName());
      e.setSender(userEnterprise.getEnterpriseName());
      e.setStatus("Pending");
      hospital.getWorkQueue().getExaminationRequestList().add(e);
      userEnterprise.getWorkQueue().getExaminationRequestList().add(e);
      populateApplicationTable();
    }//GEN-LAST:event_sendjButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateApplicationTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void DeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());    
            ExaminationRequest request =(ExaminationRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            userEnterprise.getWorkQueue().getExaminationRequestList().remove(request);
            populateApplicationTable();
        }      
    }//GEN-LAST:event_DeletejButtonActionPerformed

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
         int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());    
            ExaminationRequest request =(ExaminationRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewExamResultPanel(userProcessContainer,account,business, request));
            layout.next(userProcessContainer);    
        }      
    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());  
            String requestEnterprise= (applicationjTable.getValueAt(row,3).toString());   
            ExaminationRequest request =(ExaminationRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
//            ExaminationRequest request1 = (ExaminationRequest)business.getEnterpriseDirectory().findEnterprise(requestEnterprise).getWorkQueue().findRequestbyID(requestID);           
//            request1.setStatus("Canceled");
            request.setStatus("Canceled");           
            request.setResolveDate(new Date());
            populateApplicationTable();
        }    
    }//GEN-LAST:event_CanceljButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton;
    private javax.swing.JButton DeletejButton;
    private javax.swing.JComboBox<String> HosjComboBox;
    private javax.swing.JComboBox<String> PetjComboBox;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton sendjButton;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
