/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.PetHealth;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EuthanasiaRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyEuthanasiaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EuthanasiaJPanel
     */
       private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ApplyEuthanasiaJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount account,Enterprise userEnterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userEnterprise=userEnterprise;
        this.account=account;
        this.business=business; 
        initPetBox();
        initcompanyBox();
        populateRequestTable();     
    }
public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);  
            ArrayList<EuthanasiaRequest> worklist = userEnterprise.getWorkQueue().getEutRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                }
            }    
    } 
public void populateSearchTable(WorkRequest apl){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);      
                    Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                
              
    } 
    public void initPetBox(){
            petjComboBox.removeAllItems();
            List<Pet> petlist = userEnterprise.getPetDirectory().getPetlist();
            for (Pet object : petlist) {
                petjComboBox.addItem(object.getName());
        }
    }
      public void initcompanyBox(){
            companyjComboBox.removeAllItems();
            List<Enterprise> petlist = business.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise object : petlist) {
                if (!object.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    companyjComboBox.addItem(object.getEnterpriseName());
                }
                
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SendNewjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SearchjButton = new javax.swing.JButton();
        searchIDjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        petjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ReasonjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyjComboBox = new javax.swing.JComboBox<>();
        refreshJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        titlejTextField = new javax.swing.JTextField();
        DeletejButton = new javax.swing.JButton();
        CanceljButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Application to Hospital");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 42, -1, -1));

        SendNewjButton.setText("Send new Application");
        SendNewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendNewjButtonActionPerformed(evt);
            }
        });
        add(SendNewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel2.setText("Search Title");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 289, -1, -1));

        SearchjButton.setText("Search Application");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });
        add(SearchjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 346, -1, -1));
        add(searchIDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 284, 128, -1));

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Sender", "Reciever", "SendDate", "ExecuteDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(applicationjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 800, 150));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        jLabel3.setText("Pet");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        petjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(petjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel4.setText("Reason");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        ReasonjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReasonjTextFieldActionPerformed(evt);
            }
        });
        add(ReasonjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 230, 76));

        jLabel5.setText("Enterprise");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        companyjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(companyjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 38, -1, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));
        add(titlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 128, -1));

        DeletejButton.setText("Delete Application");
        DeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButtonActionPerformed(evt);
            }
        });
        add(DeletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        CanceljButton1.setText("Cancel Application");
        CanceljButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButton1ActionPerformed(evt);
            }
        });
        add(CanceljButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void ReasonjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReasonjTextFieldActionPerformed

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        // TODO add your handling code here:
        String search = searchIDjTextField.getText();
        WorkRequest findAccount = userEnterprise.getWorkQueue().findRequestbyname(search);
        //这里应该返回一个找到用户名字的List  //现在是返回一个网络个体
        populateSearchTable(findAccount);
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void SendNewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendNewjButtonActionPerformed
        // TODO add your handling code here:
        if (!ReasonjTextField.getText().isEmpty()) {
        Enterprise euEnterprise = business.getEnterpriseDirectory().findEnterprise(companyjComboBox.getSelectedItem().toString());
        String reason = ReasonjTextField.getText();
        Pet pet = userEnterprise.getPetDirectory().findPet(petjComboBox.getSelectedItem().toString());
        String title = titlejTextField.getText();
          
        EuthanasiaRequest euthunisiaRequest= new EuthanasiaRequest(title,reason, pet);
        euthunisiaRequest.setReceiver(euEnterprise.getEnterpriseName());
        euthunisiaRequest.setSender(userEnterprise.getEnterpriseName());
        euthunisiaRequest.setStatus("pending");
      
           
        euEnterprise.getWorkQueue().getEutRequestList().add(euthunisiaRequest);
        userEnterprise.getWorkQueue().getEutRequestList().add(euthunisiaRequest);
         JOptionPane.showMessageDialog(null, "Send successfully");
         populateRequestTable();
        }else
            JOptionPane.showMessageDialog(null, "Please add a Reason");
        
    }//GEN-LAST:event_SendNewjButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void DeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            EuthanasiaRequest request =(EuthanasiaRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            userEnterprise.getWorkQueue().getExaminationRequestList().remove(request);
            populateRequestTable();
        }
    }//GEN-LAST:event_DeletejButtonActionPerformed

    private void CanceljButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButton1ActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            String requestEnterprise= (applicationjTable.getValueAt(row,3).toString());
            EuthanasiaRequest request =(EuthanasiaRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            //            ExaminationRequest request1 = (ExaminationRequest)business.getEnterpriseDirectory().findEnterprise(requestEnterprise).getWorkQueue().findRequestbyID(requestID);
            //            request1.setStatus("Canceled");
            request.setStatus("Canceled");
            request.setResolveDate(new Date());
            populateRequestTable();
        }
    }//GEN-LAST:event_CanceljButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton1;
    private javax.swing.JButton DeletejButton;
    private javax.swing.JTextField ReasonjTextField;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton SendNewjButton;
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> companyjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> petjComboBox;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField searchIDjTextField;
    private javax.swing.JTextField titlejTextField;
    // End of variables declaration//GEN-END:variables
}
