/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole.VolunteerTrainer;

import userinterface.CustomerRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.ApplicationOfVolunteer;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class ViewVolunteerJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    private ApplicationOfVolunteer request;
    /**
     * Creates new form FillVolunteerJPanel
     */
    public ViewVolunteerJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,ApplicationOfVolunteer request) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.request=request;
        initText();
    }
    
    public void initText(){
         
        AgejTextField.setText(String.valueOf(request.getAge()));       
        GenderjTextField.setText(request.getGender());
        NamejTextField.setText(request.getName());
        TitlejTextField.setText(request.getTitle());
        introductionjTextField.setText(request.getIntroduction());
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        introductionjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        GenderjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TitlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("To be a volunteer!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 59, -1, -1));
        add(introductionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 258, 80, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 131, -1, -1));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 170, -1, -1));

        jLabel4.setText("Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 219, -1, -1));

        jLabel5.setText("Self-Introduction");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 258, -1, -1));
        add(NamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 126, 80, -1));
        add(AgejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 170, 80, -1));
        add(GenderjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 214, 80, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 99, -1, -1));
        add(TitlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 94, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessVolunteerJPanel dwjp = (ProcessVolunteerJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JTextField GenderjTextField;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JTextField TitlejTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField introductionjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
