/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ApplicationOfVolunteer;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class FillVolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FillVolunteerJPanel
     */
      private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    public FillVolunteerJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Enterprise org) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.org=org;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        GenderjTextField = new javax.swing.JTextField();
        introductionjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TitlejTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("To be a volunteer!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 59, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 151, -1, -1));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 190, -1, -1));

        jLabel4.setText("Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 239, -1, -1));

        jLabel5.setText("Self-Introduction");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 278, -1, -1));
        add(NamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 146, 80, -1));
        add(AgejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 190, 80, -1));
        add(GenderjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 234, 80, -1));
        add(introductionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 278, 80, -1));

        jButton1.setText("Send Applcation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 322, -1, -1));

        jLabel6.setText("Title");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 119, -1, -1));
        add(TitlejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 114, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ApplyVolunteerJPanel11 dwjp = (ApplyVolunteerJPanel11) component;
        dwjp.populateOrgTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Title = TitlejTextField.getText();
        String name = NamejTextField.getText();
        int age = Integer.valueOf(AgejTextField.getText());
        String Gender = GenderjTextField.getText();
        String introduction = introductionjTextField.getText();
        
       
        ApplicationOfVolunteer request = new ApplicationOfVolunteer(Title,"ApplicationOfVolunteer");
        request.setReceiver(org.getEnterpriseName());
        request.setSender(account.getUsername());
        request.setStatus("Pending");
        
        request.setIntroduction(introduction);
        request.setGender(Gender);
        request.setName(name);
        request.setAge(age);
        
        account.getWorkQueue().getWorkRequestList().add(request);
        org.getWorkQueue().getWorkRequestList().add(request);
        
        JOptionPane.showMessageDialog(null,"Send successfully");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JTextField GenderjTextField;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JTextField TitlejTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField introductionjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
