/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.ApplicationOfVolunteer;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ProcessVolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessVolunteerJPanel
     */
       private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise userEnterprise;
    public ProcessVolunteerJPanel(JPanel userProcessContainer,UserAccount account,EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business; 
        userEnterprise = business.getEnterpriseDirectory().findEnterpriseID(account.getRole().getEnterpriseID());
        populateRequestTable();
    }
 public void populateRequestTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);  
            ArrayList<WorkRequest> worklist = userEnterprise.getWorkQueue().getWorkRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    if (apl.getRequestType().equals("ApplicationOfVolunteer")) {
                         Object[] row = new Object[8];
                    row[0]= apl.getID();
                    row[1]= apl.getTitle();
                    row[2]= apl.getSender();
                    row[3]=apl.getReceiver();
                    row[4]=apl.getRequestDate();
                    row[5]=apl.getResolveDate();
                    row[6]=apl.getStatus();
                    row[7]=apl.getResult();
                    dtm.addRow(row);
                    }    
                }
            }    
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ViewjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        RefreshjButton = new javax.swing.JButton();
        AgreejButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicationjTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 95, 631, 164));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setText("My Application");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 55, -1, -1));

        ViewjButton.setText("View");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });
        add(ViewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 286, -1, -1));

        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });
        add(canceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 286, -1, -1));

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 286, -1, -1));

        RefreshjButton.setText("Refresh");
        RefreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshjButtonActionPerformed(evt);
            }
        });
        add(RefreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 55, -1, -1));

        AgreejButton.setText("Agree");
        AgreejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreejButtonActionPerformed(evt);
            }
        });
        add(AgreejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 286, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
                int id=Integer.valueOf(applicationjTable.getValueAt(row, 0).toString());       
                ApplicationOfVolunteer request =(ApplicationOfVolunteer) userEnterprise.getWorkQueue().findRequestbyID(id);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add(new ViewVolunteerJPanel(userProcessContainer,account,business,request));
                layout.next(userProcessContainer);             
        }
    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);

            request.setStatus("Finished");
            request.setResult("Canceled");
            request.setResolveDate(new Date());
            populateRequestTable();
        }
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            account.getWorkQueue().getWorkRequestList().remove(request);
            populateRequestTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void RefreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshjButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_RefreshjButtonActionPerformed

    private void AgreejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreejButtonActionPerformed
        // TODO add your handling code here:
        int row = applicationjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }else{
            int requestID= Integer.valueOf(applicationjTable.getValueAt(row,0).toString());
            WorkRequest request =(WorkRequest) userEnterprise.getWorkQueue().findRequestbyID(requestID);
            request.setResult("Approve");
            request.setResolveDate(new Date());
            request.setStatus("Finished");
            populateRequestTable();
        }
    }//GEN-LAST:event_AgreejButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgreejButton;
    private javax.swing.JButton RefreshjButton;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
