/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class ApplyPetAdoptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplyPetAdoptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    public ApplyPetAdoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        populateOrgTable();
    }
    
    public void populateOrgTable(){

            DefaultTableModel dtm = (DefaultTableModel) orgjTable.getModel();
            dtm.setRowCount(0);          
            ArrayList<Enterprise> entlist = business.getEnterpriseDirectory().getEnterpriseList();          
            if (entlist != null){               
                for(Enterprise ent : entlist){
                    if (ent.getEnterpriseType().equals(Enterprise.EnterpriseType.RescuOrganization)) {
                    Object[] row = new Object[2];
                    row[0]=ent.getEnterpriseID();
                    row[1]=ent.getEnterpriseName();
                    dtm.addRow(row);
                    }
                    
                }
            }    
    } 
    public void populatePetTable(Enterprise org){

            DefaultTableModel dtm = (DefaultTableModel) petjTable.getModel();
            dtm.setRowCount(0);           
            ArrayList<Pet> petlist = org.getPetDirectory().getPetlist();           
            if (petlist != null){                 
                for(Pet pet : petlist){
                    Object[] row = new Object[4];
                    row[0] = pet.getID();
                    row[1] = pet.getName();
                    row[2]=pet.getSpecies();
                    row[3]= pet.getAge();
                    dtm.addRow(row);
                }
            }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        petjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        choosejButton = new javax.swing.JButton();
        ViewjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        RefreshOrgjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(orgjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 289, 106));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Rescue Organiztion List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 243, -1));

        sendjButton.setText("Send Application");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });
        add(sendjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        petjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Species", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(petjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 285, 106));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Pet List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        choosejButton.setText("Choose");
        choosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosejButtonActionPerformed(evt);
            }
        });
        add(choosejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        ViewjButton.setText("View Pet");
        ViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewjButtonActionPerformed(evt);
            }
        });
        add(ViewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 22, -1, -1));

        RefreshOrgjButton.setText("Refresh");
        RefreshOrgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshOrgjButtonActionPerformed(evt);
            }
        });
        add(RefreshOrgjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 23, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else{
            String ID = petjTable.getValueAt(row, 1).toString();
            Pet pet =(Pet)org.getPetDirectory().findPet(ID);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new FillAdoptionJPanel(userProcessContainer, account, business,pet,org));
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_sendjButtonActionPerformed

    private void choosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosejButtonActionPerformed
        // TODO add your handling code here:
        int row = orgjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else {
            String Name = (String)orgjTable.getValueAt(row, 1);
            org =business.getEnterpriseDirectory().findEnterprise(Name);
            populatePetTable(org);
        }

    }//GEN-LAST:event_choosejButtonActionPerformed

    private void ViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewjButtonActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else {
            String name = petjTable.getValueAt(row,1).toString();
            Pet pet = org.getPetDirectory().findPet(name);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new ViewPetJPanel(userProcessContainer,pet));
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_ViewjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.populateApplicationTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RefreshOrgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshOrgjButtonActionPerformed
        // TODO add your handling code here:
        populateOrgTable();
    }//GEN-LAST:event_RefreshOrgjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshOrgjButton;
    private javax.swing.JButton ViewjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton choosejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orgjTable;
    private javax.swing.JTable petjTable;
    private javax.swing.JButton sendjButton;
    // End of variables declaration//GEN-END:variables
}
