/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class CustomerManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageJpanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
            
    public CustomerManageJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        petAdoptionjButton = new javax.swing.JButton();
        treatPetsjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Welcome to the Customer Center !");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 57, -1, -1));

        petAdoptionjButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        petAdoptionjButton.setText("Pet adoption");
        petAdoptionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petAdoptionjButtonActionPerformed(evt);
            }
        });
        add(petAdoptionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 278, -1));

        treatPetsjButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        treatPetsjButton.setText("Treat pets");
        treatPetsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatPetsjButtonActionPerformed(evt);
            }
        });
        add(treatPetsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 244, 278, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void petAdoptionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petAdoptionjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new PetadoptionJPanel(userProcessContainer, account, business));
        layout.next(userProcessContainer);    
                
    }//GEN-LAST:event_petAdoptionjButtonActionPerformed

    private void treatPetsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatPetsjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new TreatPetsJPanel(userProcessContainer, account, business));
        layout.next(userProcessContainer);    
                
    }//GEN-LAST:event_treatPetsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton petAdoptionjButton;
    private javax.swing.JButton treatPetsjButton;
    // End of variables declaration//GEN-END:variables
}
