/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization;
import Business.Pet.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyaoli
 */
public class PetadoptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetadoptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Enterprise org;
    public PetadoptionJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        populateOrgTable();
        populateApplicationTable();
        
       
    }
    public void populateApplicationTable(){

            DefaultTableModel dtm = (DefaultTableModel) applicationjTable.getModel();
            dtm.setRowCount(0);                 
            
            ArrayList<AdoptionRequest> worklist = account.getWorkQueue().getAdoptionkRequestList();          
            if (worklist != null){               
                for(WorkRequest apl : worklist){
                    Object[] row = new Object[7];
                    row[0]= apl.getID();
                    row[1]= apl.getSender();
                    row[2]=apl.getReceiver();
                    row[3]=apl.getRequestDate();
                    row[4]=apl.getResolveDate();
                    row[5]=apl.getStatus();
                    row[6]=apl.getResult();
                    dtm.addRow(row);
                }
            }
    }
            
    public void populateOrgTable(){

            DefaultTableModel dtm = (DefaultTableModel) orgjTable.getModel();
            dtm.setRowCount(0);          
            ArrayList<Enterprise> entlist = business.getEnterpriseDirectory().getEnterpriseList();          
            if (entlist != null){               
                for(Enterprise ent : entlist){
                    if (ent.getEnterpriseType().equals("RescuOrganization")) {
                    Object[] row = new Object[2];
                    row[0]=ent.getEnterpriseID();
                    row[1]=ent.getEnterpriseName();
                    dtm.addRow(row);
                    }
                    
                }
            }    
    } 
    public void populatePetTable(Enterprise org){

            DefaultTableModel dtm = (DefaultTableModel) petjTable.getModel();
            dtm.setRowCount(0);           
            ArrayList<Pet> petlist = org.getPetDirectory().getPetlist();           
            if (petlist != null){                 
                for(Pet pet : petlist){
                    Object[] row = new Object[3];
                    row[0] = pet.getID();
                    row[1]=pet.getSpecies();
                    row[2]= pet.getAge();
                    dtm.addRow(row);
                }
            }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        petjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        choosejButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        applicationjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(orgjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 349, 289, 106));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Rescue Organiztion List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 318, 243, -1));

        sendjButton.setText("Send Application");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });
        add(sendjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 473, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));

        petjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Species", "Age"
            }
        ));
        jScrollPane2.setViewportView(petjTable);
        if (petjTable.getColumnModel().getColumnCount() > 0) {
            petjTable.getColumnModel().getColumn(2).setHeaderValue("Age");
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 349, 285, 106));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Pet List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 318, -1, -1));

        choosejButton.setText("Choose");
        choosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosejButtonActionPerformed(evt);
            }
        });
        add(choosejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 473, -1, -1));

        applicationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Sender", "Reciever", "SendDate", "ResolveDate", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicationjTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 124, 631, 164));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setText("My Application");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 81, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        // TODO add your handling code here:
        int row = petjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }else{
             int ID = Integer.valueOf(petjTable.getValueAt(row, 0).toString());       
            Pet pet =(Pet)org.getPetDirectory().findPet(ID);       
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(new fillinformationJPanel(userProcessContainer, account, business,pet,org));
            layout.next(userProcessContainer);   
        }
       
    }//GEN-LAST:event_sendjButtonActionPerformed

    private void choosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosejButtonActionPerformed
        // TODO add your handling code here:
        int row = orgjTable.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null,"Selev a row");
            return;
        }
        String Name = (String)orgjTable.getValueAt(row, 1);
        org =business.getEnterpriseDirectory().findEnterprise(Name);
        populatePetTable(org);

    }//GEN-LAST:event_choosejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable applicationjTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton choosejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orgjTable;
    private javax.swing.JTable petjTable;
    private javax.swing.JButton sendjButton;
    // End of variables declaration//GEN-END:variables
}
