/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizationRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdoptionRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class ReviewApplicationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewApplicationJPanel
     */
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business;
    private AdoptionRequest request;
    public ReviewApplicationJPanel(JPanel userProcessContainer, AdoptionRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        
        this.account=account;
        this.business=business;
        
        budgetjTextField.setText(String.valueOf(request.getBudget()));
        descriptionjTextField.setText(request.getSelfeDes());
        budgetjTextField.setEditable(false);
        descriptionjTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        budgetjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionjTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ConfirmjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        resultjTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Annual Budget");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 144, -1, -1));
        add(budgetjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 139, 119, -1));

        jLabel5.setText("Personal Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 188, -1, -1));
        add(descriptionjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 183, 119, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Please fill in your information !");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 74, -1, -1));

        ConfirmjButton.setText("Confirm");
        ConfirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmjButtonActionPerformed(evt);
            }
        });
        add(ConfirmjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 277, -1, -1));

        jLabel6.setText("Result");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 232, -1, -1));
        add(resultjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 227, 119, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdoptionProcess dwjp = (AdoptionProcess) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_backJButtonActionPerformed

    private void ConfirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmjButtonActionPerformed
        // TODO add your handling code here:
        String result = resultjTextField.getText();
        request.setResult(result);
        request.setResolveDate(new Date());
        request.setStatus("Finished");
        JOptionPane.showMessageDialog(null, "Confirm successfully");
    }//GEN-LAST:event_ConfirmjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField budgetjTextField;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField resultjTextField;
    // End of variables declaration//GEN-END:variables
}
